theme: jekyll-theme-minimal
title: Welcome to GEOL 5303
description: This is a repository for course materials in the University of Texas at El Paso GEOL 5303 Computer Applications in the Geosciences course.
